#spring.cloud.config.server.git.uri=https://github.com/laohuzhao/MySelfProject.git/TestSpringCould/application.properties
server:
  port: 8080
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhaolaohu/stored_code.git
          username: 936423094@qq.com
          password: zhaojunhu123
